### ISSUE TITLE
[suggestion]mod memory footprint statistics

### ISSUE THREAD

**Issue by xkforce** [JarHax/Caliper#12]
Being able to break down memory usage per mod would be a really useful feature for pack makers.

**Comment by Darkhax** [comment]
Thanks for the feature request. This is something I would love to add however I don't think it will be viable or realistic to add. There is no way to accurately determine the amount of memory used by a specific mod. Doing things like reporting the memory size of a specific object is also limited to JDK tools, meaning that the average user would not be able to make use of this.
