### ISSUE TITLE
Request - A way to determine possible byte leaks.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [JarHax/Caliper#14]
So I have a large 1.12.2 pack that I need to figure out which is trying to trigger a byte overflow in the nbt reg. Can you please add a way to help me detect such an issue?

**Comment by Darkhax** [comment]
Unfortunately byte overflow leaks are not a problem that can be logged easily. If you have a byte overflow there will be an error in your log file which has a stacktrace, and this will show you what is responsible.
