### ISSUE TITLE
Crash during server startup

### ISSUE THREAD

**Issue by CREEATION** [JarHax/Caliper#15]
Minecraft: `1.12.2`
Forge: `14.23.5.2824`
Caliper: `1.1.42`

[Log](https://hastebin.com/siqumopama.md)

It does work in singleplayer, but it crashes on a real server, even though both have `Java 1.8.0_201` installed (which Caliper complains about in the log, trying to parse it).

**Comment by Darkhax** [comment]
This should prevent the crashing. The mod works under normal circumstances, but something has caused your log output to be different.

**Comment by CREEATION** [comment]
Yeah, I was pretty confused, too - this only happened once while testing, but I thought it's still worth reporting. Thanks for the fix! 🐢
