### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Saereth** [JarHax/Caliper#16]
getting an NPE on load complete
crashlog: https://gist.github.com/Saereth/894793ca6fec52bc9408fdfa068dce16

forge: 14.23.5.2836
mc: 1.12.2
caliper: 1.1.43 

Lots of mods, custom pack.

**Comment by Darkhax** [comment]
Thank you for reporting this issue. It should be fixed in the next release, which will be live on CurseForge in a few minutes.
