### ISSUE TITLE
Add registration profiling

### ISSUE THREAD

**Issue by LemADEC** [JarHax/Caliper#18]
As of 1.1.44, we're missing a measurement on how long it takes for mods to process the registration events, most notably:
minecraft:blocks
minecraft:items
minecraft:biomes
minecraft:enchantments
minecraft:entities
minecraft:potions
minecraft:potiontypes
minecraft:soundevents
minecraft:villagerprofessions
minecraft:recipes

Seeing my test modpack getting stuck for 50 s during recipe registration, I was hoping Caliper would help finding the issue.

**Comment by Darkhax** [comment]
Thanks for the feature request. The timing data is pretty frustrating to work with. Does the loading screen with Forge not show which recipe file is being registered? There should be a bit of info to give you a hint of who is taking up the load time for the short term.

**Comment by LemADEC** [comment]
When it happens, the Forge screen is a bit silent as there's no sub category telling which registry nor mod is being processed. I've found the issue from checking the logs when it's stuck.
Having a view of the total time taken for each category would be better than nothing.

**Comment by Darkhax** [comment]
Now that Forge has some of this stuff built in I don't think this is needed anymore.
