### ISSUE TITLE
Event listener info only picks up instance methods?

### ISSUE THREAD

**Issue by Mysteryem** [JarHax/Caliper#2]
I was looking at https://www.reddit.com/r/feedthebeast/comments/7dqct2/btm_pack_analysis/ and couldn't see most of the event listeners for Up And Down And All Around. Most of Up And Down's event listening methods are static and I could only see its event subscribed instance methods in the event listener info.

RegistryEvent.Register also seems to be missing from the info.

**Comment by Darkhax** [comment]
There are a few issues with the event listeners detection method. Forge doesn't really keep the context in a useful way so I have to reverse engineer a string that has all the data in it. Some strings use different formats, and so on. Right now I am catching these as unknown, however in the future I am going to be cleaning this up some more.

**Comment by Darkhax** [comment]
This has finally been fixed. https://github.com/Darkhax-Minecraft/Caliper/commit/8d4536c312a3587eb1265643280f4b4b467d873f
