### ISSUE TITLE
Crash During Startup With CraftTweaker Profiling

### ISSUE THREAD

**Issue by ChloeDawn** [JarHax/Caliper#4]
My dedicated server crashed during startup from an NPE at [ProfileCraftTweaker.java#L56](https://github.com/Darkhax-Minecraft/Caliper/blob/master/src/main/java/net/darkhax/caliper/profiling/profilers/crt/ProfileCraftTweaker.java#L56)

**Caliper version:** [1.12.2-1.1.32](https://minecraft.curseforge.com/projects/caliper/files/2539894)
**CraftTweaker version:** [1.12-4.1.5](https://minecraft.curseforge.com/projects/crafttweaker/files/2535188)

**Crash report:** [gist:f3861d574f90fd826416b0d3db32cfe6](https://gist.github.com/InsomniaKitten/f3861d574f90fd826416b0d3db32cfe6)

**Comment by Darkhax** [comment]
Could you help confirm if the fix I pushed yesterday helps solve this crash?

**Comment by Darkhax** [comment]
I will assume it was fixed.

**Comment by ChloeDawn** [comment]
Oops, sorry, forgot to respond; yeah it's fixed, thank you ^^
