### ISSUE TITLE
[Suggestion] Add a dimension registry MD file

### ISSUE THREAD

**Issue by Zer0Lyfe** [JarHax/Caliper#5]
it would be cool if you added a dimension ID Lister as it currently doesn't have it. Thanks in advance.
Zer0

**Comment by Darkhax** [comment]
Thanks for the feature request, this has been added to the latest alpha on Curse. Let me know what you think of it when you get the chance.

**Comment by Zer0Lyfe** [comment]
Thank you. It is working perfectly so far.
