### ISSUE TITLE
NPE Crash from Caliper

### ISSUE THREAD

**Issue by Vyraal1** [JarHax/Caliper#6]
https://hastebin.com/iwobixujiw.sql

**Comment by Darkhax** [comment]
Thanks for the report. I've released a new update to Bookshelf which should stop this crash. The mod will also now print out some additional information, I would appreciate if you could sent me that so I can see more info and fix the root of this bug.

**Comment by Vyraal1** [comment]
Sure thing, I updated to the latest Bookshelf (although I haven't been able to reproduce the crash again either), where is the information being printed out to that you wanted?

**Comment by Vyraal1** [comment]
And 2 hours later, I got the crash again - https://hastebin.com/wavuqiyobo.sql
Did you mean the crash report would have more information or did you also want the log?

This happened after the pack loaded, and was when I was trying to load up a saved world in single player. Happened right after I was clicking through the Forge Registry entries that were missing from removing some mods from the pack.

**Comment by Darkhax** [comment]
The latest version I was referring to was 2.3.544, you're using 2.3.543 in that second crash. Did the file somehow get reverted between your comments?

As for the fix, it will print out an error message in the log instead of crashing that will give more information about what's actually going on.

**Comment by Vyraal1** [comment]
This is going to sound silly, but I double checked and checked again and made sure that it was the latest version of Bookshelf 
![image](https://user-images.githubusercontent.com/26587049/39162528-fe8efbd4-4743-11e8-882f-fe0ab4d6670d.png)

**Comment by Vyraal1** [comment]
Ok, I goofed. I double checked the crash and log and it looks like the once I was posting yesterday (I always have my crash reports sorted by latest), but it turns out it's just crashing without a report, so this recent set might not be related to Caliper, sorry for the confusion, if I can get more confirmation I'll bring it up.
